#!/bin/sh
#
# cricket-service Cricket Service
#
# chkconfig: - 80 05
# description: Enable Cricket Service
#

### BEGIN INIT INFO
# Provides:          cricket-service
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description:       Cricket Service
# Short-Description: Enable Cricket Service
### END INIT INFO

DESC="my microservice"
NAME=cricket-service
PIDFILE=/var/run/$NAME.pid
RUN_AS=root
WORK_DIR=/opt/cricket
DAEMON=/usr/bin/java
DAEMON_OPTS="-jar gskorupa-site-1.0.0.jar -r"

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/#!/bin/sh
#
# cricket-service Cricket Service
#
# chkconfig: - 80 05
# description: Enable Cricket Service
#

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

do_start() {
    start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE \
        --background \
        --chuid $RUN_AS \
        --chdir $WORK_DIR \
        --exec $DAEMON -- $DAEMON_OPTS
}

do_stop() {
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    if [ -e $PIDFILE ]
        then rm $PIDFILE
    fi
}

case "$1" in
    start)
    echo -n "Starting $DESC: $NAME"
    do_start
    echo "."
    ;;
    stop)
    echo -n "Stopping $DESC: $NAME"
    do_stop
    echo "."
    ;;
    restart)
    echo -n "Restarting $DESC: $NAME"
    do_stop
    sleep 1
    do_start
    echo "."
    ;;
    status)
    status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;
    *)
    echo "usage: $NAME {start|stop|restart}"
    exit 1
    ;;
esac


